### ISSUE TITLE
NullPointerException pressing back after search

### ISSUE THREAD

**Issue by samuelrey** [SoftwareEngineeringDaily/SEDaily-Android#2]
1. launch app
1. submit search query
1. select any of the results
1. press back
1. NullPointerException

I had expected this use flow to return me to the results view of the query just submitted, but it actually crashes application.

**Comment by samuelrey** [comment]
> FATAL EXCEPTION: main
                                                                                                      Process: com.koalatea.thehollidayinn.softwareengineeringdaily, PID: 15452
                                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                                          at com.koalatea.thehollidayinn.softwareengineeringdaily.MainActivity.buildTransportControls(MainActivity.java:224)
                                                                                                          at com.koalatea.thehollidayinn.softwareengineeringdaily.MainActivity$1.onConnected(MainActivity.java:61)
                                                                                                          at android.support.v4.media.MediaBrowserCompat$ConnectionCallback$StubApi21.onConnected(MediaBrowserCompat.java:574)
                                                                                                          at android.support.v4.media.MediaBrowserCompatApi21$ConnectionCallbackProxy.onConnected(MediaBrowserCompatApi21.java:104)
                                                                                                          at android.media.browse.MediaBrowser$5.run(MediaBrowser.java:577)
                                                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6169)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by TheHollidayInn** [comment]
Ah, okay. This must be an issue with the music provider populating.

**Comment by TheHollidayInn** [comment]
Fixed here: https://github.com/SoftwareEngineeringDaily/SEDaily-Android/commit/5905ecf6fbce0c5f3c98705749f074c9789dd57f. 

Basically when you clicked back, the logo button was missing because search was still persistent. However, using the logo button for pausing was testing only, so I just removed it for now.
