### ISSUE TITLE
Crash When Viewing Open Source Info

### ISSUE THREAD

**Issue by TheHollidayInn** [SoftwareEngineeringDaily/SEDaily-Android#77]
## Device Details
- Device Name: 
- Android Version:
- App Version: 

## Steps to Reproduce:
1. Open app
2. Click more top right
3. Click open source info

**Include screenshots**

```
11-28 17:38:17.216 3650-4296/com.koalatea.thehollidayinn.softwareengineeringdaily.debug E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
                                                                                                          Process: com.koalatea.thehollidayinn.softwareengineeringdaily.debug, PID: 3650
                                                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                              at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
                                                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                              at java.lang.Thread.run(Thread.java:764)
                                                                                                           Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f030002
                                                                                                              at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:241)
                                                                                                              at android.content.res.Resources.getResourcePackageName(Resources.java:1948)
                                                                                                              at com.google.android.gms.internal.zzdlu.zza(Unknown Source:10)
                                                                                                              at com.google.android.gms.internal.zzdlu.zzen(Unknown Source:12)
                                                                                                              at com.google.android.gms.oss.licenses.zzb.loadInBackground(Unknown Source:4)
                                                                                                              at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
                                                                                                              at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
                                                                                                              at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
                                                                                                              at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                              at java.lang.Thread.run(Thread.java:764) 
11-28 17:38:17.317 3650-4296/com.koalatea.thehollidayinn.softwareengineeringdaily.debug E/UncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                                 at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
                                                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                                 at java.lang.Thread.run(Thread.java:764)
                                                                                                              Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f030002
                                                                                                                 at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:241)
                                                                                                                 at android.content.res.Resources.getResourcePackageName(Resources.java:1948)
                                                                                                                 at com.google.android.gms.internal.zzdlu.zza(Unknown Source:10)
                                                                                                                 at com.google.android.gms.internal.zzdlu.zzen(Unknown Source:12)
                                                                                                                 at com.google.android.gms.oss.licenses.zzb.loadInBackground(Unknown Source:4)
                                                                                                                 at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
                                                                                                                 at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
                                                                                                                 at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
                                                                                                                 at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                                 at java.lang.Thread.run(Thread.java:764) 
```

**Comment by TheHollidayInn** [comment]
I can't find the repo for Google Play OSS and this looks like an internal issue.
